### ISSUE TITLE
unnecessary flashes

### ISSUE THREAD

**Issue by jacekkopecky** [ear1grey/structured-start-tab#66]
on loading the start tab, the first link flashes after a short moment. Similarly, when shift-clicked, both the link and the "name" field flash; the name input field shouldn't.

**Comment by ear1grey** [comment]
These occur to guide the viewer to where they need to look in order to edit, and to guide them back to the link they've edited in a screenful of similar links once the edit screen has gone.  The next release will have better edit dialogs that will remove the need for flashes on edit start, bit I thin they're still needed once it's complete.  The behaviour/style of the flash may need to change though.
